scikit-hep/uhi

uhi/typing/plottable.py
This is a followup to #2, with one more possible change. This is a bit of extra typing, but is much clearer; I could see the following to be rather confusing if this is named `counts` instead of `effective_counts`, since it's not always the true number of counts, but an effective count calculation. For a user filling a weighed sum or weighed mean histogram, the fact that ".counts" is neither the number of times filled nor the weighted number of times filled is likely to be quite a surprise. While if it was called "effective_counts", they would be more likely to suspect that it's a special computed quantity and not just the raw or weighted counts.
Followup to #2, CC @HDembinski and @JPivarski.
=> docs: minor updates

uhi/typing/plottable.py
- variances should return the same as values for an ordinary unweighted histogram
- clarified wording and use of (effective) counts to compute error on the mean
=> Update on wording and change in definition of variances

docs/plotting.rst, src/uhi/typing/plottable.py
@HDembinski, @jpivarski Important fix to the protocol. The old version required writable properties for axes, kind, and traits. 🤦 . This only requires they be readable properties now. (If they are writable, it does not invalidate the protocol, but it is not _required_! Not discovered by mplhep usage because the mini-NumPy wrapper happened to have writable properties).
I'd also like to update the protocol to require returning np.ndarray from .values() and such, as you should be a bit more explicit on return types, and less explicit on accepted types. Now that `ArrayLike` is available, I realize you should only "accept" ArrayLike, and never return it, it's too broad for a return usually.
=> fix: properties are not required to be writable

.pre-commit-config.yaml, setup.cfg, src/uhi/typing/plottable.py
Making this extend `Sequence[T]` turns out to be rather hard in Python 3.6; due to the fact Generic types in 3.6 were actually objects and not classes, you couldn't inherit from one. In 3.7, this was fixed by the addition of `__class_getitem__` and a few other things, so Generics really are just normal classes (literally - in 3.9+ the built in classes now work as Generics using this). See https://github.com/python/typing/issues/561. This is also a large part of why importing the typing module in 3.7+ is 7x faster, it's not making a bunch of objects anymore, just classes.
I've added the one really useful "Sequence" method here; we could add the rest (in which case, this really would become a Sequence, as a Protocol is just that - no need to subclass), but for now, it seems this is close …
=> feat: protocol update to 1.2

.pre-commit-config.yaml, docs/plotting.rst, poetry.lock, pyproject.toml, src/uhi/numpy_plottable.py, tests/test_ensure.py
=> feat: add adaptor

pyproject.toml
Add missing test folder, fixes the conda-forge recipe testing check, using method described in python-poetry/poetry#3797 (and hopefully in the docs eventually).
Also dropping the `__init__` from tests, tests shouldn't (normally) have an init, not sure why it's there.
=> fix: add missing test folder to sdist

.github/workflows/ci.yml, environment.yml, noxfile.py, src/uhi/numpy_plottable.py, tests/test_root.py
Tested for TH1F by comparing as follows:
```python
import ROOT
h = ROOT.TH1F("h1", "h1", 50, -2.5, 2.5)
h.FillRandom("gaus", 10000)
h.Draw()
from matplotlib import pyplot as plt
fig, ax = plt.subplots()
import mplhep
mplhep.histplot(h)
plt.show()
```
The conversion to numpy exploits the fact that TH1 inherits from TArray (which can directly be converted to a numpy array) for storing the counts, and the sums of squared weights is stored as another TArray (so most could be replaced by equivalent PyROOT pythonizations in the future).
For more-dimensional histograms I put `order="F"` in the reshape such that `.values()[i,j]` equals `.GetBinContent(i+1, j+1)`, but didn't test beyond that. Overflow bins are dropped.
CC @andrzejnovak
=> feat: conversion of ROOT histograms to PlottableHistogram

.github/workflows/ci.yml, .pre-commit-config.yaml, docs/conf.py, docs/index.rst, docs/serialization.md, noxfile.py, pyproject.toml, src/uhi/resources/histogram.json, src/uhi/schema.py, tests/resources/reg.json, tests/test_histogram_schema.py
Starting a schema for serialization as discussed at PyHEP dot dev.
=> feat: add a schema for serialization

.github/workflows/cd.yml, .github/workflows/ci.yml, .pre-commit-config.yaml, README.md, docs/conf.py, pyproject.toml, src/uhi/numpy_plottable.py, src/uhi/typing/plottable.py, tests/test_root.py, tests/test_uhi.py
=> feat: modernize, Python 3.8+

.pre-commit-config.yaml, docs/indexing.rst, pyproject.toml, src/uhi/tag.py, src/uhi/testing/indexing.py, tests/test_testing.py
Starting a generic testing helper framework. For a third party to test their implementation, they can subclass the provided UnitTest fixture and implement the required methods producing histograms.
Thoughts so far:
* I could make this a Mixin, which would workaround a possible issue with discovery if you import it directly into your test file instead of keeping a dotted name. But then typing is trickier, so I haven't done that (yet).
* I could provide the suggested data contents. I think this might ideally follow serialization.
* This uses unittest not just because that avoids a dependency, but also because pytest won't rewrite an assert that's not in a test file. It can be run with pytest and still prints nicely.
Closes #133.
=> feat: starting generic testing framework

docs/indexing+.rst, docs/indexing.rst, src/uhi/tag.py, src/uhi/testing/indexing.py
This is in numpy, so let's drop it. `uhi.tag` is new and unreleased, so no need for back-compat (unlike boost-histogram).
=> fix: drop Slicer for np.s_

src/uhi/resources/histogram.schema.json, tests/resources/reg.json
This is an alternative to (close #152). This reduces nesting. This also includes one followup, supporting a URI for each array, instead of requiring arrays to be stacked into N+1 dimensions.
This modifies the schema to keep the types more consistent. When implementing it, I have to have if statements around this portion; it would be simpler if every storage had the same structure.
Now they all are structured as `storage/<fields>`, instead of `storage/data` sometimes containing fields and sometimes not.
This is a change to the schema, so I'd like sign-offs from @hdembinski and @jpivarski.
=> feat: remove data nesting

docs/serialization.md, src/uhi/resources/histogram.schema.json, tests/resources/reg.json
Limiting what can be placed in metadata. We can expand it later. Close #162.
#154 will be rebased on this, too.
=> fix: tighten metadata definition

docs/serialization.md, src/uhi/resources/histogram.schema.json, src/uhi/typing/serialization.py, tests/resources/valid/reg.json
This adds a place for library-specific metadata to be added. This allows the library and version to be recorded in the histogram. It is not required for reading.
We floated around several ideas for this name; I thought of `"vendor"` (it's was inspired by the vendor field in CMakePreset.json), and we also considered `"header"`. But since we decided to make the histogram library a key, then `"library"` seems to be fitting. Open to suggestions, though. `"writer_info"` is another option.
=> feat: add writer_info field

pyproject.toml, src/uhi/io/__init__.py, src/uhi/io/hdf5.py, src/uhi/io/json.py, src/uhi/io/zip.py, src/uhi/resources/histogram.schema.json, src/uhi/typing/serialization.py, tests/resources/valid/2d.json, tests/resources/valid/reg.json, tests/test_hdf5.py, tests/test_json.py, tests/test_zip.py
Adding read/write support, hdf5 support pulled from https://github.com/scikit-hep/boost-histogram/pull/997. Zip and JSON support added as well. Libraries supporting the UHI schema can simply produce or consume a Python object following the schema and then use the utilities in `uhi.io` to read or write to all the formats we implement.
This also makes a clarification to the schema:
* The storage format needs to support ND Arrays, so that's explicitly shown as nested lists now in the schema. For interlibrary communication, it must support `np.asarray`.
Each format remains as flexible as possible by expecting the user to do a little setup; you can store anywhere in an HDF5 file via groups. You can write to an existing zip file, control the compression, etc. by using a Zipfile object.
I'm …
=> feat: add read/write support

docs/serialization.md, src/uhi/io/__init__.py, tests/test_serialization.py
This adds the removal function, and clarifies that `None` values should be trimmed. Both from boost-histogram/hist implementation work.
=> feat: upstreaming a bit from boost-histogram/hist

pyproject.toml
Oldest version that supported 3.9.
=> chore: min version of numpy for 3.9

docs/serialization.md, src/uhi/io/_common.py, src/uhi/io/hdf5.py, src/uhi/io/zip.py, src/uhi/testing/indexing.py, src/uhi/typing/serialization.py
The error messages from mypy were confusing, since it calls `boost_histogram.Histogram` and `uhi.typing.serialization.Histogram` both `Histogram`, so let's add IR to the typed dicts representing the intermediate representation. Helps when writing docs, too.
=> refactor: use IR for intermediate representation typing helpers

src/uhi/io/_common.py, tests/resources/valid/mean.json, tests/test_serialization.py
boost-histogram 1.6.1 always adds an empty metadata dict. Let's filter it out here if we can, since empty metadata is supposed to not add the key, not add an empty dict.
=> fix: don't store empty metadata dict

pyproject.toml
Closes: https://github.com/scikit-hep/uhi/issues/211
=> Update boost-histogram version to 1.6.1
