.github/CONTRIBUTING.md, .pre-commit-config.yaml, noxfile.py, pyproject.toml, tests/test_uhi.py
Adding a nicer version bump mechanism with nox.
=> chore: tighter mypy, tooling updates

.flake8, .pre-commit-config.yaml, pyproject.toml
Puts all configuration into pyproject.toml.
=> chore: try pyproject-flake8

.flake8, .github/workflows/ci.yml, .pre-commit-config.yaml, pyproject.toml, src/uhi/numpy_plottable.py, tests/test_uhi.py
=> chore: adapt to new versions

.git_archival.txt, .gitattributes, .github/workflows/ci.yml, .gitignore, pdm.lock, pyproject.toml, src/uhi/__init__.py, src/uhi/_version.pyi
Makes releases a tiny bit quicker.
=> chore: use svn versioning

.github/workflows/ci.yml, .pre-commit-config.yaml, docs/conf.py, noxfile.py, pyproject.toml, src/uhi/__init__.py, src/uhi/_version.pyi, src/uhi/numpy_plottable.py, src/uhi/typing/plottable.py, tests/test_ensure.py, tests/test_root.py, tests/test_uhi.py
=> chore: drop Python 3.6

.flake8, .pre-commit-config.yaml, pyproject.toml, src/uhi/numpy_plottable.py
=> chore: move to using Ruff

.github/workflows/ci.yml, .pre-commit-config.yaml, docs/indexing+.rst, pyproject.toml
Addressing some warnings from sp-repo-review.
- chore: make sp-repo-review happier
- docs: fix typo in code
=> chore: sp-repo-review

.github/workflows/cd.yml, .github/workflows/ci.yml, .pre-commit-config.yaml, docs/conf.py, noxfile.py, pyproject.toml
- chore: prepare for schema addition
- chore: bump pre-commit
=> docs: prepare for schema addition

.pre-commit-config.yaml
=> chore: add a check and bump NumPy

docs/changelog.md, docs/conf.py, docs/index.rst, pyproject.toml
=> docs: add changelog

.pre-commit-config.yaml, src/uhi/schema.py
Fix for old name still present.
=> fix: one more schema ending issue

.github/dependabot.yml, .github/release.yml, pyproject.toml
=> chore: more minor modernizations

pyproject.toml
=> tests: require fastjsonschema

src/uhi/typing/serialization.py
=> fix: typing update for recent change

src/uhi/testing/indexing.py, tests/test_testing.py
Split up the tests into 1D and 3D tests. See https://github.com/scikit-hep/uhi/issues/168.
- **feat: split up tests by dimensions**
- **refactor: use simpler names**
=> feat: split up test by dimension

src/uhi/testing/indexing.py, tests/test_testing.py
=> tests: add 2d tests

src/uhi/testing/indexing.py
=> feat: wrap bins in generic tests

CITATION.cff, README.md
Close https://github.com/scikit-hep/uhi/issues/77.
=> chore: add CITATION file

.pre-commit-config.yaml, src/uhi/io/zip.py, src/uhi/typing/serialization.py, tests/test_hdf5.py, tests/test_zip.py
Adding tests for the rest of the formats for hist and boost-histogram.
=> tests: add hdf5 and zip tests

tests/conftest.py, tests/test_hdf5.py, tests/test_histogram_schema.py, tests/test_json.py, tests/test_zip.py
=> tests: add fixture for valid/invalid

src/uhi/testing/indexing.py, tests/test_testing.py
Now that we have uhi serialization, let's provide it for the indexing tests.
=> fix(tests): provide uhi serialized form

.github/release.yml, pyproject.toml
=> chore: prepare for 1.0

docs/testing.md
While looking at this great major release 1.0.0 I noticed the copy-paste typos for 2D and 3D and ended up putting the docs fully in sync with the code.
=> Update and fix testing.md

.pre-commit-config.yaml, pyproject.toml, tests/conftest.py
See https://github.com/scikit-hep/uhi/issues/211.
=> tests: show current packages of interest
